#!/bin/bash

echo "🧹 Chrome Extension Cleanup Helper"
echo "=================================="
echo ""

echo "🚨 IMPORTANT: This script helps with Chrome cleanup procedures"
echo "It does NOT modify your extension files - only provides guidance"
echo ""

echo "📋 CURRENT STATUS:"
echo "=================="
echo "❌ Extension error persists: Cannot read properties of undefined (reading 'extensionId')"
echo "🔍 Extension ID found: nifkkiakealklbopapnpgneocmafcknp"
echo "💡 This indicates Chrome extension system corruption"
echo ""

echo "🔄 REQUIRED ACTIONS:"
echo "===================="
echo "1. COMPLETE EXTENSION REMOVAL"
echo "   - Go to chrome://extensions/"
echo "   - Find TabOracle and REMOVE completely"
echo "   - Close Chrome entirely (all windows)"
echo ""

echo "2. CHROME PROCESS CLEANUP"
echo "   - Wait 10 seconds after closing Chrome"
echo "   - Check for any remaining Chrome processes:"
echo "     ps aux | grep chrome"
echo "   - Kill any remaining processes if found"
echo ""

echo "3. CHROME DATA CLEARING (if needed)"
echo "   - Go to chrome://settings/clearBrowserData"
echo "   - Select: Cached images and files"
echo "   - Select: Cookies and other site data"
echo "   - Click 'Clear data'"
echo ""

echo "4. REINSTALL EXTENSION"
echo "   - Reopen Chrome fresh"
echo "   - Go to chrome://extensions/"
echo "   - Enable Developer mode"
echo "   - Load unpacked: /home/sig9moid/code/cursor"
echo ""

echo "🧪 TESTING PROCEDURE:"
echo "====================="
echo "After reinstallation:"
echo "1. Open test-minimal.html in Chrome"
echo "2. Click 'Test Ping' button"
echo "3. Click 'Test Get Tabs' button"
echo "4. Check for any errors in console"
echo ""

echo "💡 TROUBLESHOOTING TIPS:"
echo "========================"
echo "- Always close Chrome completely after removing extensions"
echo "- Test in incognito mode if issues persist"
echo "- Check Chrome's extension error logs"
echo "- Verify all permissions are granted"
echo ""

echo "🚀 Ready to proceed with cleanup!"
echo "================================="
echo ""
echo "Press Enter to continue or Ctrl+C to cancel..."
read -r

echo "📋 NEXT STEPS:"
echo "=============="
echo "1. Follow the complete extension reset steps above"
echo "2. Test with test-minimal.html"
echo "3. Report results back"
echo "4. If successful, restore full functionality"
echo ""
echo "Good luck! 🍀"
