#!/bin/bash

echo "🔧 TabOracle Extension Troubleshooting Script"
echo "=============================================="
echo ""

echo "📋 Current Status:"
echo "=================="
echo "✅ Minimal extension files created"
echo "✅ Backup files saved"
echo "✅ Test page created"
echo ""

echo "🚨 ERROR ANALYSIS:"
echo "=================="
echo "The error 'Cannot read properties of undefined (reading extensionId)'"
echo "indicates Chrome's extension system is corrupted."
echo ""

echo "🔄 RECOMMENDED SOLUTION:"
echo "========================"
echo "1. COMPLETE EXTENSION RESET (Required)"
echo "   - Remove TabOracle from chrome://extensions/"
echo "   - Close Chrome completely"
echo "   - Reopen Chrome"
echo "   - Install the minimal version first"
echo ""

echo "2. TEST WITH MINIMAL VERSION"
echo "   - Current manifest: minimal (tabs permission only)"
echo "   - Current background: minimal (basic functionality)"
echo "   - Test file: test-minimal.html"
echo ""

echo "3. GRADUAL FEATURE RESTORATION"
echo "   - If minimal works, add storage permission"
echo "   - If that works, add scripting permission"
echo "   - If that works, restore full functionality"
echo ""

echo "📁 FILES TO TEST:"
echo "=================="
echo "✅ test-minimal.html - Test the minimal extension"
echo "✅ manifest.json - Current minimal manifest"
echo "✅ background.js - Current minimal background script"
echo ""

echo "🔍 TESTING STEPS:"
echo "=================="
echo "1. Open test-minimal.html in Chrome"
echo "2. Click 'Test Ping' button"
echo "3. Click 'Test Get Tabs' button"
echo "4. Check for any errors in console"
echo ""

echo "📝 NEXT ACTIONS:"
echo "================"
echo "1. Follow the complete extension reset steps above"
echo "2. Test with test-minimal.html"
echo "3. Report results back"
echo "4. Gradually restore features if minimal works"
echo ""

echo "💡 TROUBLESHOOTING TIPS:"
echo "========================"
echo "- Always close Chrome completely after removing extensions"
echo "- Test in incognito mode if issues persist"
echo "- Check Chrome's extension error logs"
echo "- Verify all permissions are granted"
echo ""

echo "🚀 Ready to troubleshoot!"
echo "========================="
